<div class="powered-by">
            <a rel="datafaqs:powered_by" href="http://www.w3.org/TR/rdfa-syntax">
               <img src="image/sw-rdfa-orange.png" alt="Powered by RDFa" width="120px"/></a>
            <a rel="datafaqs:powered_by" href="http://test.ckan.net/">
               <img src="https://github.com/timrdf/DataFAQs/raw/master/doc/ckan/ckan_logo_box.png" alt="Powered by CKAN" width="80px"/></a>
            <a rel="datafaqs:powered_by" href="http://sadiframework.org/content/">
               <img src="https://github.com/timrdf/DataFAQs/raw/master/doc/sadi/sadi-header.png" alt="Powered by SADI" width="150px"/></a>
            <a rel="datafaqs:powered_by" href="http://code.google.com/p/surfrdf/">
               <img src="http://surfrdf.googlecode.com/files/surf-logo-poweredby.png" alt="Powered by SuRF" width="150px"/></a>
            <a rel="datafaqs:powered_by" href="http://lodspeakr.org">
               <img src="http://lodspeakr.org/img/lodspeakr_small.png" alt="Powered by LODSPeaKr" width="100px"/></a>
            <p>
               <a rel="doap:developer" xmlns:foaf="http://xmlns.com/foaf/0.1/" href="http://tw.rpi.edu/instances/TimLebo">
                  <span property="foaf:name" class="deemphasize">Tim Lebo</span>
                  <span rel="rdf:type"       class="deemphasize" resource="[foaf:Person]"/>
               </a>
            </p>
         </div>
